'use strict';

/**
 * Names of the objects created by the adapter, in all languages required for the repository.
 */
const labels = {
    adapters: {
        en: 'Monitored adapters',
        de: 'Überwachte Adapter',
        ru: 'Отслеживаемые адаптеры',
        pt: 'Adaptadores monitorados',
        nl: 'Bewaakte adapters',
        fr: 'Adaptateurs surveillés',
        it: 'Adattatori monitorati',
        es: 'Adaptadores supervisados',
        pl: 'Monitorowane adaptery',
        uk: 'Адаптери під наглядом',
        'zh-cn': '受监控的适配器',
    },
    summary: {
        en: 'Summary',
        de: 'Zusammenfassung',
        ru: 'Сводка',
        pt: 'Resumo',
        nl: 'Overzicht',
        fr: 'Résumé',
        it: 'Riepilogo',
        es: 'Resumen',
        pl: 'Podsumowanie',
        uk: 'Підсумок',
        'zh-cn': '摘要',
    },
    installedVersion: {
        en: 'Installed version',
        de: 'Installierte Version',
        ru: 'Установленная версия',
        pt: 'Versão instalada',
        nl: 'Geïnstalleerde versie',
        fr: 'Version installée',
        it: 'Versione installata',
        es: 'Versión instalada',
        pl: 'Zainstalowana wersja',
        uk: 'Встановлена версія',
        'zh-cn': '已安装版本',
    },
    latestVersion: {
        en: 'Latest version on GitHub',
        de: 'Neueste Version auf GitHub',
        ru: 'Последняя версия на GitHub',
        pt: 'Versão mais recente no GitHub',
        nl: 'Nieuwste versie op GitHub',
        fr: 'Dernière version sur GitHub',
        it: 'Ultima versione su GitHub',
        es: 'Última versión en GitHub',
        pl: 'Najnowsza wersja na GitHub',
        uk: 'Остання версія на GitHub',
        'zh-cn': 'GitHub 上的最新版本',
    },
    updateAvailable: {
        en: 'Update available',
        de: 'Update verfügbar',
        ru: 'Доступно обновление',
        pt: 'Atualização disponível',
        nl: 'Update beschikbaar',
        fr: 'Mise à jour disponible',
        it: 'Aggiornamento disponibile',
        es: 'Actualización disponible',
        pl: 'Dostępna aktualizacja',
        uk: 'Доступне оновлення',
        'zh-cn': '有可用更新',
    },
    releaseNotes: {
        en: 'Release notes',
        de: 'Versionshinweise',
        ru: 'Примечания к выпуску',
        pt: 'Notas de versão',
        nl: 'Release-opmerkingen',
        fr: 'Notes de version',
        it: 'Note di rilascio',
        es: 'Notas de la versión',
        pl: 'Informacje o wydaniu',
        uk: 'Примітки до випуску',
        'zh-cn': '发行说明',
    },
    releaseUrl: {
        en: 'Release page',
        de: 'Release-Seite',
        ru: 'Страница выпуска',
        pt: 'Página da versão',
        nl: 'Releasepagina',
        fr: 'Page de la version',
        it: 'Pagina del rilascio',
        es: 'Página de la versión',
        pl: 'Strona wydania',
        uk: 'Сторінка випуску',
        'zh-cn': '发布页面',
    },
    readmeUrl: {
        en: 'README of this version',
        de: 'README dieser Version',
        ru: 'README этой версии',
        pt: 'README desta versão',
        nl: 'README van deze versie',
        fr: 'README de cette version',
        it: 'README di questa versione',
        es: 'README de esta versión',
        pl: 'README tej wersji',
        uk: 'README цієї версії',
        'zh-cn': '此版本的 README',
    },
    repository: {
        en: 'GitHub repository',
        de: 'GitHub-Repository',
        ru: 'Репозиторий GitHub',
        pt: 'Repositório GitHub',
        nl: 'GitHub-repository',
        fr: 'Dépôt GitHub',
        it: 'Repository GitHub',
        es: 'Repositorio de GitHub',
        pl: 'Repozytorium GitHub',
        uk: 'Репозиторій GitHub',
        'zh-cn': 'GitHub 仓库',
    },
    lastCheck: {
        en: 'Last check',
        de: 'Letzte Prüfung',
        ru: 'Последняя проверка',
        pt: 'Última verificação',
        nl: 'Laatste controle',
        fr: 'Dernière vérification',
        it: 'Ultimo controllo',
        es: 'Última comprobación',
        pl: 'Ostatnie sprawdzenie',
        uk: 'Остання перевірка',
        'zh-cn': '上次检查',
    },
    updatesCount: {
        en: 'Number of available updates',
        de: 'Anzahl verfügbarer Updates',
        ru: 'Количество доступных обновлений',
        pt: 'Número de atualizações disponíveis',
        nl: 'Aantal beschikbare updates',
        fr: 'Nombre de mises à jour disponibles',
        it: 'Numero di aggiornamenti disponibili',
        es: 'Número de actualizaciones disponibles',
        pl: 'Liczba dostępnych aktualizacji',
        uk: 'Кількість доступних оновлень',
        'zh-cn': '可用更新数量',
    },
    updateList: {
        en: 'List of available updates (JSON)',
        de: 'Liste verfügbarer Updates (JSON)',
        ru: 'Список доступных обновлений (JSON)',
        pt: 'Lista de atualizações disponíveis (JSON)',
        nl: 'Lijst met beschikbare updates (JSON)',
        fr: 'Liste des mises à jour disponibles (JSON)',
        it: 'Elenco degli aggiornamenti disponibili (JSON)',
        es: 'Lista de actualizaciones disponibles (JSON)',
        pl: 'Lista dostępnych aktualizacji (JSON)',
        uk: 'Список доступних оновлень (JSON)',
        'zh-cn': '可用更新列表 (JSON)',
    },
};

module.exports = { labels };
